name: postgres-db
services:
  postgres:
    container_name: 'db_shop'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shop_api'
      - 'POSTGRES_PASSWORD=Db@User2025!'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: