name: shop-api-stack

services:
  postgres:
    container_name: 'db_shop'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shop_api'
      - 'POSTGRES_PASSWORD=Db@User2025!'
    ports:
      - '5432:5432'  # Porta 5433 tanto no host quanto no container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -p 5432  # Força PostgreSQL a rodar na porta 5433
    networks:
      - shop-network

  app:
    container_name: 'shop-api'
    build: .
    ports:
      - '5400:5400'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shop_api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Db@User2025!
    networks:
      - shop-network

volumes:
  postgres_data:

networks:
  shop-network:
    driver: bridge
