#services:
  #mysql:
   # container_name: 'guide-mysql'
    #image: 'mysql:latest'
    #environment:
    #  - 'MYSQL_DATABASE=shop_api'
    #  - 'MYSQL_PASSWORD=Db@User2025!'
    #  - 'MYSQL_ROOT_PASSWORD=password'
     # - 'MYSQL_USER=dev_app_user'
    #ports:
    #  - '3306:3306'